from typing import Protocol

from vcf_api.variants.models import PageRequest, PageResult, VariantRecord


class VariantRepository(Protocol):
    def validate_source(self) -> None: ...

    def revision(self) -> str: ...

    def list(self, request: PageRequest) -> PageResult: ...

    def create(self, variant: VariantRecord) -> None: ...

    def update_by_id(self, variant_id: str, variant: VariantRecord) -> int: ...

    def delete_by_id(self, variant_id: str) -> int: ...
